### ISSUE TITLE
method to reconstruct garment

### ISSUE THREAD

**Issue by msverma101** [rlczddl/awesome-3d-human-reconstruction#5]
I am also trying to do some form of avatar reconstruction for my thesis.
i have tried colmap, Neus, anchorUDF, ICON there are artifacts in most of them or it needs a lot of images.
Most the papers that i surveyed does not have any code.
do you mind suggesting me what i can use that is fast and gives me good quality surface reconstruction for garments from one or few images

**Comment by rlczddl** [comment]
May be https://github.com/SangHunHan92/2K2K and https://github.com/facebookresearch/pifuhd can help you.
